[package]
name = "evcxr_repl"
version = "0.3.2"
license = "Apache-2.0"
description = "A REPL for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = ["David Lattimore <dvdlttmr@google.com>"]

[dependencies]
evcxr = { version = "=0.3.2", path = "../evcxr" }
rustyline = "=1.0.0"
colored = "=1.6.1"
dirs = "=1.0.4"
lazy_static = "=1.2.0"
failure = { version = "=0.1.3", default-features = false, features = [ "std" ] }
regex = "=1.1.0"
